'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace hisQuirofano
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CxPendientesResponseDataWrapper", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CxPendientesResponseDataWrapper
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatosCasoBPMField As hisQuirofano.BackLog
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoRespuestaField As hisQuirofano.EstadoRespuesta
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DatosCasoBPM() As hisQuirofano.BackLog
            Get
                Return Me.DatosCasoBPMField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DatosCasoBPMField, value) <> true) Then
                    Me.DatosCasoBPMField = value
                    Me.RaisePropertyChanged("DatosCasoBPM")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstadoRespuesta() As hisQuirofano.EstadoRespuesta
            Get
                Return Me.EstadoRespuestaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoRespuestaField, value) <> true) Then
                    Me.EstadoRespuestaField = value
                    Me.RaisePropertyChanged("EstadoRespuesta")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BackLog", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BackLog
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrdenCxField() As hisQuirofano.OrdenCx
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrdenCx() As hisQuirofano.OrdenCx()
            Get
                Return Me.OrdenCxField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrdenCxField, value) <> true) Then
                    Me.OrdenCxField = value
                    Me.RaisePropertyChanged("OrdenCx")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EstadoRespuesta", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EstadoRespuesta
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoRespuestaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoRespuesta() As String
            Get
                Return Me.CodigoRespuestaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoRespuestaField, value) <> true) Then
                    Me.CodigoRespuestaField = value
                    Me.RaisePropertyChanged("CodigoRespuesta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mensaje() As String
            Get
                Return Me.MensajeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeField, value) <> true) Then
                    Me.MensajeField = value
                    Me.RaisePropertyChanged("Mensaje")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrdenCx", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrdenCx
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApellidoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CamaDestinoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoPacienteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CuitFinanciadorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CuitProfesionalResponsableField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionCirugiaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiagnosticoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EquipamientoField As hisQuirofano.Equipamiento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaHoraSolicitadaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaModificadaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaNacimientoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HistoriaClinicaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IntubacionDificultosaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MaterialesField As hisQuirofano.Materiales
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NivelUrgenciaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreCompletoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NroCasoBpmField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NroDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NroFormularioHISField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NroReaperturaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PacienteAlergicoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PacienteInternadoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcedimientosField As hisQuirofano.Procedimientos
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReaperturaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequiereAnatomiaPatologicaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequiereRXField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequiereSangreField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SexoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoAnestesiaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoFormularioHISField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioSolicitanteField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Apellido() As String
            Get
                Return Me.ApellidoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApellidoField, value) <> true) Then
                    Me.ApellidoField = value
                    Me.RaisePropertyChanged("Apellido")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CamaDestino() As String
            Get
                Return Me.CamaDestinoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CamaDestinoField, value) <> true) Then
                    Me.CamaDestinoField = value
                    Me.RaisePropertyChanged("CamaDestino")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoPaciente() As Integer
            Get
                Return Me.CodigoPacienteField
            End Get
            Set
                If (Me.CodigoPacienteField.Equals(value) <> true) Then
                    Me.CodigoPacienteField = value
                    Me.RaisePropertyChanged("CodigoPaciente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CuitFinanciador() As String
            Get
                Return Me.CuitFinanciadorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CuitFinanciadorField, value) <> true) Then
                    Me.CuitFinanciadorField = value
                    Me.RaisePropertyChanged("CuitFinanciador")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CuitProfesionalResponsable() As String
            Get
                Return Me.CuitProfesionalResponsableField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CuitProfesionalResponsableField, value) <> true) Then
                    Me.CuitProfesionalResponsableField = value
                    Me.RaisePropertyChanged("CuitProfesionalResponsable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DescripcionCirugia() As String
            Get
                Return Me.DescripcionCirugiaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionCirugiaField, value) <> true) Then
                    Me.DescripcionCirugiaField = value
                    Me.RaisePropertyChanged("DescripcionCirugia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Diagnostico() As String
            Get
                Return Me.DiagnosticoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DiagnosticoField, value) <> true) Then
                    Me.DiagnosticoField = value
                    Me.RaisePropertyChanged("Diagnostico")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Equipamiento() As hisQuirofano.Equipamiento
            Get
                Return Me.EquipamientoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EquipamientoField, value) <> true) Then
                    Me.EquipamientoField = value
                    Me.RaisePropertyChanged("Equipamiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaHoraSolicitada() As String
            Get
                Return Me.FechaHoraSolicitadaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaHoraSolicitadaField, value) <> true) Then
                    Me.FechaHoraSolicitadaField = value
                    Me.RaisePropertyChanged("FechaHoraSolicitada")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaModificada() As Boolean
            Get
                Return Me.FechaModificadaField
            End Get
            Set
                If (Me.FechaModificadaField.Equals(value) <> true) Then
                    Me.FechaModificadaField = value
                    Me.RaisePropertyChanged("FechaModificada")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaNacimiento() As String
            Get
                Return Me.FechaNacimientoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaNacimientoField, value) <> true) Then
                    Me.FechaNacimientoField = value
                    Me.RaisePropertyChanged("FechaNacimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HistoriaClinica() As Integer
            Get
                Return Me.HistoriaClinicaField
            End Get
            Set
                If (Me.HistoriaClinicaField.Equals(value) <> true) Then
                    Me.HistoriaClinicaField = value
                    Me.RaisePropertyChanged("HistoriaClinica")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IntubacionDificultosa() As Integer
            Get
                Return Me.IntubacionDificultosaField
            End Get
            Set
                If (Me.IntubacionDificultosaField.Equals(value) <> true) Then
                    Me.IntubacionDificultosaField = value
                    Me.RaisePropertyChanged("IntubacionDificultosa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Materiales() As hisQuirofano.Materiales
            Get
                Return Me.MaterialesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaterialesField, value) <> true) Then
                    Me.MaterialesField = value
                    Me.RaisePropertyChanged("Materiales")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NivelUrgencia() As String
            Get
                Return Me.NivelUrgenciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NivelUrgenciaField, value) <> true) Then
                    Me.NivelUrgenciaField = value
                    Me.RaisePropertyChanged("NivelUrgencia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombre() As String
            Get
                Return Me.NombreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreField, value) <> true) Then
                    Me.NombreField = value
                    Me.RaisePropertyChanged("Nombre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreCompleto() As String
            Get
                Return Me.NombreCompletoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreCompletoField, value) <> true) Then
                    Me.NombreCompletoField = value
                    Me.RaisePropertyChanged("NombreCompleto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NroCasoBpm() As Integer
            Get
                Return Me.NroCasoBpmField
            End Get
            Set
                If (Me.NroCasoBpmField.Equals(value) <> true) Then
                    Me.NroCasoBpmField = value
                    Me.RaisePropertyChanged("NroCasoBpm")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NroDocumento() As String
            Get
                Return Me.NroDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NroDocumentoField, value) <> true) Then
                    Me.NroDocumentoField = value
                    Me.RaisePropertyChanged("NroDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NroFormularioHIS() As String
            Get
                Return Me.NroFormularioHISField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NroFormularioHISField, value) <> true) Then
                    Me.NroFormularioHISField = value
                    Me.RaisePropertyChanged("NroFormularioHIS")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NroReapertura() As Integer
            Get
                Return Me.NroReaperturaField
            End Get
            Set
                If (Me.NroReaperturaField.Equals(value) <> true) Then
                    Me.NroReaperturaField = value
                    Me.RaisePropertyChanged("NroReapertura")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PacienteAlergico() As Integer
            Get
                Return Me.PacienteAlergicoField
            End Get
            Set
                If (Me.PacienteAlergicoField.Equals(value) <> true) Then
                    Me.PacienteAlergicoField = value
                    Me.RaisePropertyChanged("PacienteAlergico")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PacienteInternado() As Integer
            Get
                Return Me.PacienteInternadoField
            End Get
            Set
                If (Me.PacienteInternadoField.Equals(value) <> true) Then
                    Me.PacienteInternadoField = value
                    Me.RaisePropertyChanged("PacienteInternado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Procedimientos() As hisQuirofano.Procedimientos
            Get
                Return Me.ProcedimientosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcedimientosField, value) <> true) Then
                    Me.ProcedimientosField = value
                    Me.RaisePropertyChanged("Procedimientos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Reapertura() As Boolean
            Get
                Return Me.ReaperturaField
            End Get
            Set
                If (Me.ReaperturaField.Equals(value) <> true) Then
                    Me.ReaperturaField = value
                    Me.RaisePropertyChanged("Reapertura")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequiereAnatomiaPatologica() As Boolean
            Get
                Return Me.RequiereAnatomiaPatologicaField
            End Get
            Set
                If (Me.RequiereAnatomiaPatologicaField.Equals(value) <> true) Then
                    Me.RequiereAnatomiaPatologicaField = value
                    Me.RaisePropertyChanged("RequiereAnatomiaPatologica")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequiereRX() As Integer
            Get
                Return Me.RequiereRXField
            End Get
            Set
                If (Me.RequiereRXField.Equals(value) <> true) Then
                    Me.RequiereRXField = value
                    Me.RaisePropertyChanged("RequiereRX")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequiereSangre() As Boolean
            Get
                Return Me.RequiereSangreField
            End Get
            Set
                If (Me.RequiereSangreField.Equals(value) <> true) Then
                    Me.RequiereSangreField = value
                    Me.RaisePropertyChanged("RequiereSangre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sexo() As String
            Get
                Return Me.SexoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SexoField, value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoAnestesia() As String
            Get
                Return Me.TipoAnestesiaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoAnestesiaField, value) <> true) Then
                    Me.TipoAnestesiaField = value
                    Me.RaisePropertyChanged("TipoAnestesia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.TipoDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoDocumentoField, value) <> true) Then
                    Me.TipoDocumentoField = value
                    Me.RaisePropertyChanged("TipoDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoFormularioHIS() As String
            Get
                Return Me.TipoFormularioHISField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoFormularioHISField, value) <> true) Then
                    Me.TipoFormularioHISField = value
                    Me.RaisePropertyChanged("TipoFormularioHIS")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsuarioSolicitante() As String
            Get
                Return Me.UsuarioSolicitanteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioSolicitanteField, value) <> true) Then
                    Me.UsuarioSolicitanteField = value
                    Me.RaisePropertyChanged("UsuarioSolicitante")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Equipamiento", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Equipamiento
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EquipoField() As hisQuirofano.Equipo
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Equipo() As hisQuirofano.Equipo()
            Get
                Return Me.EquipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EquipoField, value) <> true) Then
                    Me.EquipoField = value
                    Me.RaisePropertyChanged("Equipo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Materiales", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Materiales
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MaterialField() As hisQuirofano.Material
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Material() As hisQuirofano.Material()
            Get
                Return Me.MaterialField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaterialField, value) <> true) Then
                    Me.MaterialField = value
                    Me.RaisePropertyChanged("Material")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Procedimientos", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Procedimientos
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcedimientoField() As hisQuirofano.Procedimiento
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Procedimiento() As hisQuirofano.Procedimiento()
            Get
                Return Me.ProcedimientoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcedimientoField, value) <> true) Then
                    Me.ProcedimientoField = value
                    Me.RaisePropertyChanged("Procedimiento")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Equipo", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Equipo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Material", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Material
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CantidadField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoBPMField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoSapField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionMaterialesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MarcaSugeridadField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cantidad() As Integer
            Get
                Return Me.CantidadField
            End Get
            Set
                If (Me.CantidadField.Equals(value) <> true) Then
                    Me.CantidadField = value
                    Me.RaisePropertyChanged("Cantidad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoBPM() As String
            Get
                Return Me.CodigoBPMField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoBPMField, value) <> true) Then
                    Me.CodigoBPMField = value
                    Me.RaisePropertyChanged("CodigoBPM")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoSap() As String
            Get
                Return Me.CodigoSapField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoSapField, value) <> true) Then
                    Me.CodigoSapField = value
                    Me.RaisePropertyChanged("CodigoSap")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DescripcionMateriales() As String
            Get
                Return Me.DescripcionMaterialesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionMaterialesField, value) <> true) Then
                    Me.DescripcionMaterialesField = value
                    Me.RaisePropertyChanged("DescripcionMateriales")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MarcaSugeridad() As String
            Get
                Return Me.MarcaSugeridadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MarcaSugeridadField, value) <> true) Then
                    Me.MarcaSugeridadField = value
                    Me.RaisePropertyChanged("MarcaSugeridad")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Procedimiento", [Namespace]:="http://schemas.datacontract.org/2004/07/HISMiddleware.Modules.OrdenesMedicas.Mode"& _ 
        "ls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Procedimiento
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CPTField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CajaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionProcedimientoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LadoCirugiaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NivelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrincipalField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CPT() As String
            Get
                Return Me.CPTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CPTField, value) <> true) Then
                    Me.CPTField = value
                    Me.RaisePropertyChanged("CPT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Caja() As String
            Get
                Return Me.CajaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CajaField, value) <> true) Then
                    Me.CajaField = value
                    Me.RaisePropertyChanged("Caja")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DescripcionProcedimiento() As String
            Get
                Return Me.DescripcionProcedimientoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionProcedimientoField, value) <> true) Then
                    Me.DescripcionProcedimientoField = value
                    Me.RaisePropertyChanged("DescripcionProcedimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LadoCirugia() As String
            Get
                Return Me.LadoCirugiaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LadoCirugiaField, value) <> true) Then
                    Me.LadoCirugiaField = value
                    Me.RaisePropertyChanged("LadoCirugia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nivel() As String
            Get
                Return Me.NivelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NivelField, value) <> true) Then
                    Me.NivelField = value
                    Me.RaisePropertyChanged("Nivel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Principal() As Boolean
            Get
                Return Me.PrincipalField
            End Get
            Set
                If (Me.PrincipalField.Equals(value) <> true) Then
                    Me.PrincipalField = value
                    Me.RaisePropertyChanged("Principal")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="hisQuirofano.IOrdenesMedicasService")>  _
    Public Interface IOrdenesMedicasService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrdenesMedicasService/ObtenerCxPendientes_000078CNS", ReplyAction:="http://tempuri.org/IOrdenesMedicasService/ObtenerCxPendientes_000078CNSResponse")>  _
        Function ObtenerCxPendientes_000078CNS(ByVal CaseNumber As Integer, ByVal FechaDesde As String, ByVal FechaHasta As String, ByVal TipoFormulario As String, ByVal NumeroFormulario As String, ByVal IdServicio As String, ByVal CodigoPaciente As Integer, ByVal HistoriaClinica As Integer) As hisQuirofano.CxPendientesResponseDataWrapper
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrdenesMedicasService/ObtenerCxPendientes_000078CNS", ReplyAction:="http://tempuri.org/IOrdenesMedicasService/ObtenerCxPendientes_000078CNSResponse")>  _
        Function ObtenerCxPendientes_000078CNSAsync(ByVal CaseNumber As Integer, ByVal FechaDesde As String, ByVal FechaHasta As String, ByVal TipoFormulario As String, ByVal NumeroFormulario As String, ByVal IdServicio As String, ByVal CodigoPaciente As Integer, ByVal HistoriaClinica As Integer) As System.Threading.Tasks.Task(Of hisQuirofano.CxPendientesResponseDataWrapper)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrdenesMedicasService/PlanificarCirugia_000082ABM", ReplyAction:="http://tempuri.org/IOrdenesMedicasService/PlanificarCirugia_000082ABMResponse")>  _
        Function PlanificarCirugia_000082ABM(ByVal CodigoPaciente As Integer, ByVal TipoOrden As String, ByVal NumeroOrden As String, ByVal NroCasoBpm As Integer, ByVal FechaPlanificada As String, ByVal Suspendido As Boolean, ByVal Cancelado As Boolean, ByVal QxAsignado As String, ByVal Motivo As String, ByVal UsuarioNovedad As String, ByVal Comentarios As String) As hisQuirofano.EstadoRespuesta
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrdenesMedicasService/PlanificarCirugia_000082ABM", ReplyAction:="http://tempuri.org/IOrdenesMedicasService/PlanificarCirugia_000082ABMResponse")>  _
        Function PlanificarCirugia_000082ABMAsync(ByVal CodigoPaciente As Integer, ByVal TipoOrden As String, ByVal NumeroOrden As String, ByVal NroCasoBpm As Integer, ByVal FechaPlanificada As String, ByVal Suspendido As Boolean, ByVal Cancelado As Boolean, ByVal QxAsignado As String, ByVal Motivo As String, ByVal UsuarioNovedad As String, ByVal Comentarios As String) As System.Threading.Tasks.Task(Of hisQuirofano.EstadoRespuesta)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOrdenesMedicasServiceChannel
        Inherits hisQuirofano.IOrdenesMedicasService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OrdenesMedicasServiceClient
        Inherits System.ServiceModel.ClientBase(Of hisQuirofano.IOrdenesMedicasService)
        Implements hisQuirofano.IOrdenesMedicasService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtenerCxPendientes_000078CNS(ByVal CaseNumber As Integer, ByVal FechaDesde As String, ByVal FechaHasta As String, ByVal TipoFormulario As String, ByVal NumeroFormulario As String, ByVal IdServicio As String, ByVal CodigoPaciente As Integer, ByVal HistoriaClinica As Integer) As hisQuirofano.CxPendientesResponseDataWrapper Implements hisQuirofano.IOrdenesMedicasService.ObtenerCxPendientes_000078CNS
            Return MyBase.Channel.ObtenerCxPendientes_000078CNS(CaseNumber, FechaDesde, FechaHasta, TipoFormulario, NumeroFormulario, IdServicio, CodigoPaciente, HistoriaClinica)
        End Function
        
        Public Function ObtenerCxPendientes_000078CNSAsync(ByVal CaseNumber As Integer, ByVal FechaDesde As String, ByVal FechaHasta As String, ByVal TipoFormulario As String, ByVal NumeroFormulario As String, ByVal IdServicio As String, ByVal CodigoPaciente As Integer, ByVal HistoriaClinica As Integer) As System.Threading.Tasks.Task(Of hisQuirofano.CxPendientesResponseDataWrapper) Implements hisQuirofano.IOrdenesMedicasService.ObtenerCxPendientes_000078CNSAsync
            Return MyBase.Channel.ObtenerCxPendientes_000078CNSAsync(CaseNumber, FechaDesde, FechaHasta, TipoFormulario, NumeroFormulario, IdServicio, CodigoPaciente, HistoriaClinica)
        End Function
        
        Public Function PlanificarCirugia_000082ABM(ByVal CodigoPaciente As Integer, ByVal TipoOrden As String, ByVal NumeroOrden As String, ByVal NroCasoBpm As Integer, ByVal FechaPlanificada As String, ByVal Suspendido As Boolean, ByVal Cancelado As Boolean, ByVal QxAsignado As String, ByVal Motivo As String, ByVal UsuarioNovedad As String, ByVal Comentarios As String) As hisQuirofano.EstadoRespuesta Implements hisQuirofano.IOrdenesMedicasService.PlanificarCirugia_000082ABM
            Return MyBase.Channel.PlanificarCirugia_000082ABM(CodigoPaciente, TipoOrden, NumeroOrden, NroCasoBpm, FechaPlanificada, Suspendido, Cancelado, QxAsignado, Motivo, UsuarioNovedad, Comentarios)
        End Function
        
        Public Function PlanificarCirugia_000082ABMAsync(ByVal CodigoPaciente As Integer, ByVal TipoOrden As String, ByVal NumeroOrden As String, ByVal NroCasoBpm As Integer, ByVal FechaPlanificada As String, ByVal Suspendido As Boolean, ByVal Cancelado As Boolean, ByVal QxAsignado As String, ByVal Motivo As String, ByVal UsuarioNovedad As String, ByVal Comentarios As String) As System.Threading.Tasks.Task(Of hisQuirofano.EstadoRespuesta) Implements hisQuirofano.IOrdenesMedicasService.PlanificarCirugia_000082ABMAsync
            Return MyBase.Channel.PlanificarCirugia_000082ABMAsync(CodigoPaciente, TipoOrden, NumeroOrden, NroCasoBpm, FechaPlanificada, Suspendido, Cancelado, QxAsignado, Motivo, UsuarioNovedad, Comentarios)
        End Function
    End Class
End Namespace
